# Generated by Django 4.2.11 on 2024-09-25 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xauth', '0006_alter_faculty_faculty_code'),
        ('fyp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100)),
                ('project_title', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xauth.department')),
                ('students', models.ManyToManyField(to='xauth.student')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='xauth.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyDepartmentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xauth.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xauth.faculty')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyp.role')),
            ],
            options={
                'unique_together': {('faculty', 'department', 'role')},
            },
        ),
    ]
