# Generated by Django 4.2.11 on 2024-09-30 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xauth', '0006_alter_faculty_faculty_code'),
        ('fyp', '0002_role_projectgroup_facultydepartmentrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_done', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('presentation_required', models.BooleanField(default=False)),
                ('weightage', models.FloatField(default=0.0)),
                ('total_score', models.FloatField(default=100.0)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester_name', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='projectgroup',
            name='department',
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=100)),
                ('credits', models.PositiveIntegerField(default=3)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xauth.degree')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyp.semester')),
                ('students', models.ManyToManyField(to='xauth.student')),
            ],
        ),
        migrations.CreateModel(
            name='CLO',
            fields=[
                ('clo_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('clo_number', models.PositiveIntegerField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fyp.course')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentCriteria',
            fields=[
                ('criteria_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('max_score', models.FloatField(default=0.0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='fyp.assessment')),
                ('clo_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fyp.clo')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='clo_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fyp.clo'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyp.semester'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fyp.course'),
            preserve_default=False,
        ),
    ]
