# Generated by Django 4.2.11 on 2024-09-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0003_assessment_semester_remove_projectgroup_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectgroup',
            name='group_name',
        ),
    ]
