# Generated by Django 4.2.11 on 2024-09-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xauth', '0006_alter_faculty_faculty_code'),
        ('fyp', '0004_remove_projectgroup_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgroup',
            name='students',
            field=models.ManyToManyField(blank=True, to='xauth.student'),
        ),
    ]
