# Generated by Django 4.2.11 on 2024-09-30 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xauth', '0006_alter_faculty_faculty_code'),
        ('fyp', '0005_alter_projectgroup_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyp.course')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_groups', to='xauth.student')),
                ('members', models.ManyToManyField(blank=True, related_name='member_groups', to='xauth.student')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectGroup',
        ),
    ]
