# Generated by Django 4.2.11 on 2024-09-30 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xauth', '0006_alter_faculty_faculty_code'),
        ('fyp', '0007_remove_group_leader_remove_group_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmembership',
            name='role',
        ),
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='fyp.group')),
                ('invited_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='xauth.student')),
            ],
        ),
    ]
