# Generated by Django 4.2.11 on 2024-09-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0009_group_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentGroup',
        ),
    ]
