# Generated by Django 4.2.11 on 2024-09-30 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0010_delete_studentgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='semester',
        ),
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fyp.course'),
            preserve_default=False,
        ),
    ]
