# Generated by Django 4.2.11 on 2024-09-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0012_clo_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='clo_link',
        ),
        migrations.AddField(
            model_name='assessment',
            name='clos',
            field=models.ManyToManyField(blank=True, related_name='assessments', to='fyp.clo'),
        ),
    ]
