# Generated by Django 4.2.11 on 2024-09-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0013_remove_assessment_clo_link_assessment_clos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='total_score',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='clos',
            field=models.ManyToManyField(blank=True, to='fyp.clo'),
        ),
    ]
