# Generated by Django 4.2.11 on 2024-09-30 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xauth', '0006_alter_faculty_faculty_code'),
        ('fyp', '0014_remove_assessment_total_score_alter_assessment_clos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialities', models.ManyToManyField(related_name='supervisors', to='fyp.speciality')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xauth.faculty')),
            ],
        ),
    ]
