# Generated by Django 4.2.11 on 2024-09-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0015_speciality_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='specialities',
            field=models.ManyToManyField(blank=True, related_name='supervisors', to='fyp.speciality'),
        ),
    ]
