# Generated by Django 4.2.11 on 2024-09-30 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0016_alter_supervisor_specialities'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_message', models.TextField()),
                ('description', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervision_requests', to='fyp.group')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyp.supervisor')),
            ],
        ),
    ]
