# Generated by Django 4.2.11 on 2024-09-30 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0017_supervisionrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specialty',
        ),
    ]
