# Generated by Django 4.2.11 on 2024-10-03 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xauth', '0006_alter_faculty_faculty_code'),
        ('fyp', '0020_alter_fypidea_supervisor_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='FypManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_limit', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('group_size', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('course', models.ManyToManyField(blank=True, to='fyp.course')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xauth.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_awarded', models.FloatField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyp.group')),
            ],
        ),
        migrations.CreateModel(
            name='PanelInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PanelMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.ManyToManyField(blank=True, related_name='panelmembers', to='fyp.speciality')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xauth.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('room_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('deadline', models.CharField(max_length=100)),
                ('file', models.ImageField(upload_to='file')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyp.course')),
            ],
        ),
        migrations.RenameField(
            model_name='assessmentcriteria',
            old_name='name',
            new_name='criteria',
        ),
        migrations.RemoveField(
            model_name='assessmentcriteria',
            name='description',
        ),
        migrations.AddField(
            model_name='assessment',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xauth.faculty'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.AddField(
            model_name='presentation',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyp.assessment'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyp.course'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyp.fypmanager'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='student_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyp.group'),
        ),
        migrations.AddField(
            model_name='panelinvitation',
            name='panel_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyp.panelmember'),
        ),
        migrations.AddField(
            model_name='panelinvitation',
            name='presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyp.presentation'),
        ),
        migrations.AddField(
            model_name='panelinvitation',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fyp.fypmanager'),
        ),
        migrations.AddField(
            model_name='groupmarks',
            name='panel_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyp.panelmember'),
        ),
        migrations.AddField(
            model_name='groupmarks',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyp.assessmentcriteria'),
        ),
    ]
