# Generated by Django 4.2.11 on 2024-10-03 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0021_fypmanager_groupmarks_panelinvitation_panelmember_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('supervisor_type', models.BooleanField(default=True)),
                ('organization', models.CharField(blank=True, max_length=200, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('specialities', models.ManyToManyField(blank=True, related_name='external_supervisors', to='fyp.speciality')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='second_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fyp.secondsupervisor'),
        ),
    ]
