# Generated by Django 4.2.11 on 2024-12-18 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xauth', '0006_alter_faculty_faculty_code'),
        ('fyp', '0022_secondsupervisor_group_second_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=10)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='panelinvitation',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fyp.course'),
        ),
        migrations.AddField(
            model_name='panelinvitation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xauth.faculty'),
        ),
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xauth.degree'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fyp.semester'),
        ),
        migrations.AlterField(
            model_name='fypmanager',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xauth.faculty'),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyp.course')),
            ],
        ),
    ]
