# Generated by Django 4.2.11 on 2024-12-20 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0023_timetableentry_panelinvitation_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='section_name',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='fyp.group'),
        ),
    ]
