# Generated by Django 4.2.11 on 2024-12-20 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xauth', '0006_alter_faculty_faculty_code'),
        ('fyp', '0024_course_section_name_alter_groupmembership_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable_json',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_name', to='xauth.faculty'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='file',
            field=models.FileField(upload_to='timetables/'),
        ),
    ]
