# Generated by Django 4.2.11 on 2024-12-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xauth', '0006_alter_faculty_faculty_code'),
        ('fyp', '0025_timetable_json_alter_supervisor_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='panel_members',
            field=models.ManyToManyField(blank=True, to='xauth.faculty'),
        ),
    ]
