# Generated by Django 4.2.11 on 2024-12-29 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0026_presentation_panel_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='created_by',
        ),
    ]
