# Generated by Django 4.2.11 on 2024-12-29 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0027_remove_presentation_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fyp.fypmanager'),
            preserve_default=False,
        ),
    ]
