# Generated by Django 4.2.11 on 2024-12-29 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0028_presentation_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='created_by',
        ),
    ]
