# Generated by Django 4.2.11 on 2024-12-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0029_remove_presentation_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
