# Generated by Django 4.2.11 on 2025-01-11 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xauth', '0006_alter_faculty_faculty_code'),
        ('fyp', '0030_alter_presentation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmarks',
            name='panel_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xauth.faculty'),
        ),
    ]
