# Generated by Django 4.2.11 on 2025-01-11 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0031_alter_groupmarks_panel_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmarks',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fyp.course'),
            preserve_default=False,
        ),
    ]
