# Generated by Django 4.2.11 on 2025-01-11 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xauth', '0006_alter_faculty_faculty_code'),
        ('fyp', '0032_groupmarks_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmarks',
            old_name='marks_awarded',
            new_name='marks',
        ),
        migrations.AddField(
            model_name='groupmarks',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xauth.student'),
            preserve_default=False,
        ),
    ]
