# Generated by Django 4.2.11 on 2025-01-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0034_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
